# Generated by Django 3.0.8 on 2020-08-19 05:49

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietRestrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_restrictions', multiselectfield.db.fields.MultiSelectField(choices=[('vegan', 'vegan'), ('vegetarian', 'vegetarian'), ('gluten-free', 'gluten-free'), ('wheat-free', 'wheat-free'), ('tree-nut-free', 'tree-nut-free'), ('soy-free', 'soy-free'), ('shellfish-free', 'shellfish-free'), ('sesame-free', 'sesame-free'), ('low-sugar', 'low-sugar'), ('no-oil-added', 'no-oil-added'), ('mustard-free', 'mustard-free')], max_length=125)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='diet_restrictions',
            field=models.ManyToManyField(to='users.DietRestrictions'),
        ),
    ]
