# Generated by Django 3.0.8 on 2020-08-22 21:05

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200818_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diet_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('wheat_free', 'Wheat Free'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('nut_free', 'Nut Free'), ('soy_free', 'Soy Free'), ('organic', 'Organic'), ('no_preservatives', 'No Preservatives'), ('pork_free', 'Pork Free'), ('pescetarian', 'Pescetarian'), ('peanut_free', 'Peanut Free'), ('sugar_free', 'Sugar Free'), ('no_added_sugar', 'No Added Sugar'), ('kosher', 'Kosher'), ('gluten_free', 'Gluten free'), ('fish_free', 'Fish Free'), ('egg_free', 'Egg Free'), ('diary_free', 'Diary Free'), ('non_alcoholic', 'Non Alcoholic')], default=['vegan'], max_length=193),
        ),
    ]
